#include <cpp11.hpp>
#include <cpp11/declarations.hpp>
#include <boost/math/distributions.hpp>
#include "../boostmath/macros.hpp"

TERNARY_DISTRIBUTION_BOOST(arcsine, double, double, double)
BINARY_DISTRIBUTION_BOOST(bernoulli, int, double)
TERNARY_DISTRIBUTION_BOOST(beta, double, double, double)
TERNARY_DISTRIBUTION_BOOST(binomial, int, int, double)
TERNARY_DISTRIBUTION_BOOST(cauchy, double, double, double)
BINARY_DISTRIBUTION_BOOST(chi_squared, double, double)
BINARY_DISTRIBUTION_BOOST(exponential, double, double)
TERNARY_DISTRIBUTION_BOOST(extreme_value, double, double, double)
TERNARY_DISTRIBUTION_BOOST(fisher_f, double, double, double)
TERNARY_DISTRIBUTION_BOOST(gamma, double, double, double)
BINARY_DISTRIBUTION_BOOST(geometric, double, double)
TERNARY_DISTRIBUTION_BOOST(hyperexponential, double, std::vector<double>, std::vector<double>)
QUARTERNARY_DISTRIBUTION_BOOST(hypergeometric, uint64_t, uint64_t, uint64_t, uint64_t)
TERNARY_DISTRIBUTION_BOOST(inverse_chi_squared, double, double, double)
TERNARY_DISTRIBUTION_BOOST(inverse_gamma, double, double, double)
TERNARY_DISTRIBUTION_BOOST(inverse_gaussian, double, double, double)
BINARY_DISTRIBUTION_BOOST(kolmogorov_smirnov, double, int)
TERNARY_DISTRIBUTION_BOOST(laplace, double, double, double)
TERNARY_DISTRIBUTION_BOOST(logistic, double, double, double)
TERNARY_DISTRIBUTION_BOOST(lognormal, double, double, double)
TERNARY_DISTRIBUTION_BOOST(negative_binomial, double, double, double)
QUARTERNARY_DISTRIBUTION_BOOST(non_central_beta, double, double, double, double)
TERNARY_DISTRIBUTION_BOOST(non_central_chi_squared, double, double, double)
QUARTERNARY_DISTRIBUTION_BOOST(non_central_f, double, double, double, double)
TERNARY_DISTRIBUTION_BOOST(non_central_t, double, double, double)
TERNARY_DISTRIBUTION_BOOST(normal, double, double, double)
TERNARY_DISTRIBUTION_BOOST(pareto, double, double, double)
BINARY_DISTRIBUTION_BOOST(poisson, double, double)
BINARY_DISTRIBUTION_BOOST(rayleigh, double, double)
QUARTERNARY_DISTRIBUTION_BOOST(skew_normal, double, double, double, double)
BINARY_DISTRIBUTION_BOOST(students_t, double, double)
QUARTERNARY_DISTRIBUTION_BOOST(triangular, double, double, double, double)
TERNARY_DISTRIBUTION_BOOST(uniform, double, double, double)
TERNARY_DISTRIBUTION_BOOST(weibull, double, double, double)
