#include "special_functions/airy_functions.cpp"
#include "special_functions/basic_functions.cpp"
#include "special_functions/bessel_functions.cpp"
#include "special_functions/beta_functions.cpp"
#include "special_functions/elliptic_integrals.cpp"
#include "special_functions/error_functions.cpp"
#include "special_functions/exponential_integrals.cpp"
#include "special_functions/factorials_and_binomial_coefficients.cpp"
#include "special_functions/gamma_functions.cpp"
#include "special_functions/hypergeometric_functions.cpp"
#include "special_functions/inverse_hyperbolic_functions.cpp"
#include "special_functions/jacobi_elliptic_functions.cpp"
#include "special_functions/jacobi_theta_functions.cpp"
#include "special_functions/lambert_w_function.cpp"
#include "special_functions/number_series.cpp"
#include "special_functions/owens_t_function.cpp"
#include "special_functions/polynomials.cpp"
#include "special_functions/zeta_functions.cpp"
#include "special_functions/sinus_cardinal_hyperbolic_functions.cpp"

#include "quadrature_and_differentiation/double_exponential.cpp"
#include "quadrature_and_differentiation/fourier_integrals.cpp"
#include "quadrature_and_differentiation/trapezoidal.cpp"
#include "quadrature_and_differentiation/gauss_legendre.cpp"
#include "quadrature_and_differentiation/gauss_kronrod.cpp"
#include "quadrature_and_differentiation/numerical_differentiation.cpp"

#include "statistical_distributions/statistical_distributions.cpp"

#include "vector_functionals/norms.cpp"

#include "rootfinding_and_minimisation/without_derivatives.cpp"
#include "rootfinding_and_minimisation/with_derivatives.cpp"
#include "rootfinding_and_minimisation/cubic_roots.cpp"
#include "rootfinding_and_minimisation/quartic_roots.cpp"
#include "rootfinding_and_minimisation/minima.cpp"
