#include "special_functions/airy_functions.cpp"
#include "special_functions/basic_functions.cpp"
#include "special_functions/bessel_functions.cpp"
#include "special_functions/beta_functions.cpp"
#include "special_functions/elliptic_integrals.cpp"
#include "special_functions/error_functions.cpp"
#include "special_functions/exponential_integrals.cpp"
#include "special_functions/factorials_and_binomial_coefficients.cpp"
#include "special_functions/gamma_functions.cpp"
#include "special_functions/hypergeometric_functions.cpp"
#include "special_functions/inverse_hyperbolic_functions.cpp"
#include "special_functions/jacobi_elliptic_functions.cpp"
#include "special_functions/jacobi_theta_functions.cpp"
#include "special_functions/lambert_w_function.cpp"
#include "special_functions/number_series.cpp"
#include "special_functions/owens_t_function.cpp"
#include "special_functions/polynomials.cpp"
#include "special_functions/riemann_zeta_function.cpp"
#include "special_functions/sinus_cardinal_hyperbolic_functions.cpp"

#include "quadrature_and_differentiation/trapezoidal.cpp"
#include "quadrature_and_differentiation/gauss_legendre.cpp"
#include "quadrature_and_differentiation/gauss_kronrod.cpp"
#include "quadrature_and_differentiation/numerical_differentiation.cpp"

#include "statistical_distributions/arcsine.cpp"
#include "statistical_distributions/bernoulli.cpp"
#include "statistical_distributions/beta.cpp"
